### ISSUE TITLE
What is a canadian toolchain?

### ISSUE THREAD

**Issue by midrare** [trcrsired/Portable-Cpp-Guideline#3]
> To ensure maximum portability, it is recommended to build and test your code on as many GCC cross/**canadian** toolchains as possible.

What is a canadian toolchain 🇨🇦?

**Comment by trcrsired** [comment]
canadian means hosted toolchain that does not run on build machine. For example, you try to create a Windows GCC on Linux.

**Comment by midrare** [comment]
Oh ok, I've never heard about this before. Thanks for the explanation.
